#
# TransFig makefile
#

all: 00000.tex 00001.tex 00002.tex canceling.tex charge.tex engaged.tex fault1.tex fault2.tex fault3.tex frown.tex group1.tex need.tex offline.tex printer1.tex printing.tex queued.tex rejecting.tex smile.tex stopt.tex 

# translation into epic

00000.tex: 00000.fig Makefile
	fig2dev -L epic 00000.fig > 00000.tex
clean::
	rm -f 00000.tex

00000.eps: 00000.fig Makefile
	fig2dev -L eps 00000.fig > 00000.eps
clean::
	rm -f 00000.eps


# translation into epic

00001.tex: 00001.fig Makefile
	fig2dev -L epic 00001.fig > 00001.tex
clean::
	rm -f 00001.tex

00001.eps: 00001.fig Makefile
	fig2dev -L eps 00001.fig > 00001.eps
clean::
	rm -f 00001.eps


# translation into epic

00002.tex: 00002.fig Makefile
	fig2dev -L epic 00002.fig > 00002.tex
clean::
	rm -f 00002.tex

00002.eps: 00002.fig Makefile
	fig2dev -L eps 00002.fig > 00002.eps
clean::
	rm -f 00002.eps


# translation into epic

canceling.tex: canceling.fig Makefile
	fig2dev -L epic canceling.fig > canceling.tex
clean::
	rm -f canceling.tex

canceling.eps: canceling.fig Makefile
	fig2dev -L eps canceling.fig > canceling.eps
clean::
	rm -f canceling.eps


# translation into epic

charge.tex: charge.fig Makefile
	fig2dev -L epic charge.fig > charge.tex
clean::
	rm -f charge.tex

charge.eps: charge.fig Makefile
	fig2dev -L eps charge.fig > charge.eps
clean::
	rm -f charge.eps


# translation into epic

engaged.tex: engaged.fig Makefile
	fig2dev -L epic engaged.fig > engaged.tex
clean::
	rm -f engaged.tex

engaged.eps: engaged.fig Makefile
	fig2dev -L eps engaged.fig > engaged.eps
clean::
	rm -f engaged.eps


# translation into epic

fault1.tex: fault1.fig Makefile
	fig2dev -L epic fault1.fig > fault1.tex
clean::
	rm -f fault1.tex

fault1.eps: fault1.fig Makefile
	fig2dev -L eps fault1.fig > fault1.eps
clean::
	rm -f fault1.eps


# translation into epic

fault2.tex: fault2.fig Makefile
	fig2dev -L epic fault2.fig > fault2.tex
clean::
	rm -f fault2.tex

fault2.eps: fault2.fig Makefile
	fig2dev -L eps fault2.fig > fault2.eps
clean::
	rm -f fault2.eps


# translation into epic

fault3.tex: fault3.fig Makefile
	fig2dev -L epic fault3.fig > fault3.tex
clean::
	rm -f fault3.tex

fault3.eps: fault3.fig Makefile
	fig2dev -L eps fault3.fig > fault3.eps
clean::
	rm -f fault3.eps


# translation into epic

frown.tex: frown.fig Makefile
	fig2dev -L epic frown.fig > frown.tex
clean::
	rm -f frown.tex

frown.eps: frown.fig Makefile
	fig2dev -L eps frown.fig > frown.eps
clean::
	rm -f frown.eps


# translation into epic

group1.tex: group1.fig Makefile
	fig2dev -L epic group1.fig > group1.tex
clean::
	rm -f group1.tex

group1.eps: group1.fig Makefile
	fig2dev -L eps group1.fig > group1.eps
clean::
	rm -f group1.eps


# translation into epic

need.tex: need.fig Makefile
	fig2dev -L epic need.fig > need.tex
clean::
	rm -f need.tex

need.eps: need.fig Makefile
	fig2dev -L eps need.fig > need.eps
clean::
	rm -f need.eps


# translation into epic

offline.tex: offline.fig Makefile
	fig2dev -L epic offline.fig > offline.tex
clean::
	rm -f offline.tex

offline.eps: offline.fig Makefile
	fig2dev -L eps offline.fig > offline.eps
clean::
	rm -f offline.eps


# translation into epic

printer1.tex: printer1.fig Makefile
	fig2dev -L epic printer1.fig > printer1.tex
clean::
	rm -f printer1.tex

printer1.eps: printer1.fig Makefile
	fig2dev -L eps printer1.fig > printer1.eps
clean::
	rm -f printer1.eps


# translation into epic

printing.tex: printing.fig Makefile
	fig2dev -L epic printing.fig > printing.tex
clean::
	rm -f printing.tex

printing.eps: printing.fig Makefile
	fig2dev -L eps printing.fig > printing.eps
clean::
	rm -f printing.eps


# translation into epic

queued.tex: queued.fig Makefile
	fig2dev -L epic queued.fig > queued.tex
clean::
	rm -f queued.tex

queued.eps: queued.fig Makefile
	fig2dev -L eps queued.fig > queued.eps
clean::
	rm -f queued.eps


# translation into epic

rejecting.tex: rejecting.fig Makefile
	fig2dev -L epic rejecting.fig > rejecting.tex
clean::
	rm -f rejecting.tex

rejecting.eps: rejecting.fig Makefile
	fig2dev -L eps rejecting.fig > rejecting.eps
clean::
	rm -f rejecting.eps


# translation into epic

smile.tex: smile.fig Makefile
	fig2dev -L epic smile.fig > smile.tex
clean::
	rm -f smile.tex

smile.eps: smile.fig Makefile
	fig2dev -L eps smile.fig > smile.eps
clean::
	rm -f smile.eps


# translation into epic

stopt.tex: stopt.fig Makefile
	fig2dev -L epic stopt.fig > stopt.tex
clean::
	rm -f stopt.tex

stopt.eps: stopt.fig Makefile
	fig2dev -L eps stopt.fig > stopt.eps
clean::
	rm -f stopt.eps

