#
# uprint-lpstat.1.pod
# Copyright 1998, Trinity College Computing Center.
# Written by David Chappell.
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose and without fee is hereby granted, provided
# that the above copyright notice appear in all copies and that both that
# copyright notice and this permission notice appear in supporting
# documentation.  This software and documentation are provided "as is" without
# express or implied warranty.
#
# Last modified 10 April 1998.
#

=head1 NAME

uprint-lpstat - Cancels print jobs

=head1 SYNOPSIS

B<uprint-lpstat>

=head1 DESCRIPTION

This program is part of the PPR Uprint suite.  See the UPRINT(1) man page
for an explanation of what this means.

This command attempts to emulate lpstat(1) from System V Unix.  Though it
recognizes most of lpstat(1)'s options, its implementation of some of them
is simplistic.  It is just adequate to satisfy GUI programs on Solaris.

=over 4

=item B<-a>

=item B<-c>

=item B<-p>

=item B<-d>

=item B<-D>

=item B<-f>


=back

=head1 AUTHOR

David Chappell, Trinity College Computing Center, Hartford, Connecticut.

=cut

