#!/bin/sh

# This should be run by the user "ppr", so make the id output
# part of the test:
id | sed -e 's/[ \t]*groups=.*$//' -e 's/=[0-9]*(/=?(/g'

# Set up a test print queue:
$PPAD_PATH delete regression-test1 >/dev/null 2>&1
$PPAD_PATH interface regression-test1 $TESTBIN/test_interface_2 $REGTEST_INTERFACE_OUTPUT
echo "ppad: $?"
$PPAD_PATH jobbreak regression-test1 none
echo "ppad: $?"

exit 0
