#! /bin/sh

#fig2dev -L png -g '#f0f0f0' $1.fig >$1.png
#convert -transparency '#f0f0f0' $1.png $1.gif

fig2dev -L gif -g '#f0f0f0' $1.fig >$1-temp.gif
giftrans -t '#f0f0f0' $1-temp.gif >$1.gif
rm $1-temp.gif

uuencode -m $1.gif <$1.gif | sed -e '/^begin-base64/d' -e '/^====$/d' >$1.gif.base64

ls -l $1.*


