#!/bin/sh

# Test the lp filter's placement of gutters

$HOMEDIR/filters/filter_lp 'duplex=undef gutter=1.0 orientation=portrait' "testprn" "" <${TEST_BASENAME}.in

$HOMEDIR/filters/filter_lp 'duplex=none gutter=1.0 orientation=portrait' "testprn" "" <${TEST_BASENAME}.in

$HOMEDIR/filters/filter_lp 'duplex=notumble gutter=1.0 orientation=portrait' "testprn" "" <${TEST_BASENAME}.in

$HOMEDIR/filters/filter_lp 'duplex=tumble gutter=1.0 orientation=portrait' "testprn" "" <${TEST_BASENAME}.in

$HOMEDIR/filters/filter_lp 'duplex=undef gutter=1.0 orientation=landscape' "testprn" "" <${TEST_BASENAME}.in

$HOMEDIR/filters/filter_lp 'duplex=none gutter=1.0 orientation=landscape' "testprn" "" <${TEST_BASENAME}.in

$HOMEDIR/filters/filter_lp 'duplex=notumble gutter=1.0 orientation=landscape' "testprn" "" <${TEST_BASENAME}.in

$HOMEDIR/filters/filter_lp 'duplex=tumble gutter=1.0 orientation=landscape' "testprn" "" <${TEST_BASENAME}.in

exit 0
