#! /bin/sh

# Make sure the test queue is ok:
$PPOP_PATH list regression-test1
echo "clear_output: ppop: $?"
$PPOP_PATH status regression-test1
echo "clear_output: ppop: $?"

# Remove any previous output:
rm -f $REGTEST_INTERFACE_OUTPUT
echo "clear_output: rm: $?"

exit 0

