#! /bin/sh

echo "Dumping configuration file..."
cat $CONFDIR/printers/$1
echo

echo "Use ppad to dump the configuration..."
$HOMEDIR/bin/ppad show $1
echo "ppad: $?"
echo

echo "Do it again in machine-readable mode..."
$HOMEDIR/bin/ppad -M show $1
echo "ppad: $?"
echo

exit 0
