#! /bin/sh

echo "Dumping configuration file..."
cat $CONFDIR/printers/$1
echo

echo "Use ppad to dump the configuration..."
$PPAD_PATH show $1
echo "ppad: $?"
echo

echo "Do it again in machine-readable mode..."
$PPAD_PATH -M show $1
echo "ppad: $?"
echo

exit 0
