#! /bin/sh

echo "Dumping configuration file..."
cat $CONFDIR/groups/$1
echo

echo "Use ppad to dump the configuration..."
$PPAD_PATH group show $1
echo "ppad: $?"
echo

echo "Do it again in machine-readable mode..."
$PPAD_PATH -M group show $1
echo "ppad: $?"
echo

exit 0
