#
# mouse:~ppr/src/docs/pprhack/Makefile
# Copyright 1995--2001, Trinity College Computing Center.
# Written by David Chappell.
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose and without fee is hereby granted, provided
# that the above copyright notice appear in all copies and that both that
# copyright notice and this permission notice appear in supporting
# documentation.  This software is provided "as is" without express or
# implied warranty.
#
# Last modified 20 April 2001.
#

include ../../makeprogs/global.mk
include ../rules.mk

#=== Inventory ==============================================================


#=== Build ==================================================================

all: 

#=== Install ================================================================

install:

#=== Housekeeping ===========================================================

clean:
	$(RMF) *.$(OBJ) $(BACKUPS)

# end of file
