#
# mouse:~ppr/src/docs/refman/lprsrv.8.pod
# Copyright 1995--2006, Trinity College Computing Center.
# Written by David Chappell.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
#
# Last modified 10 April 2006.
#

=head1 NAME

lprsrv - PPR RFC 1179 (lpr/lpd) server

lprsrv.conf - Access control file

lprsrv-test - Access control test program

=head1 SYNOPSIS

B<lprsrv> I<options>

B<lprsrv-test> I<hostname> [I<username>] ...


=head1 DESCRIPTION

The B<--help> option prints a brief description of the options.
The B<--version> option prints the PPR version information.

B<lprsrv> is an RFC-1179 (Berkeley lpr/lpd) compatible print server.  It
will accept print jobs over the network and hand them to B<ppr> for 
processing.

=head2 Disabling Other RFC 1179 Servers

If you want to run B<lprsrv> on the standard port (and you almost certainly do),
you must disable any RFC 1179 server already running on that port.  This
section contains instructions for disabling various RFC 1179 servers. 
If your system's print server isn't covered in this section and you figure
out how to disable it, please send the necessary instructions to
ppr-bugs@trincoll.edu.

=head3 Berkely LPD

If you are using B<lpd> from Berkely (which is popular on Linux),
you must either run B<lprsrv> on a port other than 515, or you must arrange
for B<inetd> to be started before B<lpd>.  If B<inetd> is started before B<lpd>,
B<lpd> will be unable to bind to port 515 but will still work in other respects
and B<lprsrv> will pass remote jobs to B<lpr>.  (Unfortunately, some versions
of B<lpd> will die when they fail to bind to the port.  Can anyone give
better advice than this?)

=head3 LPR-NG

If you are using LPR-NG, you must add a line such as this to F</etc/lpd.conf>:

 lpd_port=1501

You can choose any unused port that you wish.  If you wish you can also restrict
access to the loopback device:

 lpd_port=127.0.0.1%1501

You should then restart lpd.

=head3 IRIX

If you are using IRIX 6.3, you should edit F</etc/init.d/lp> and find the place
where F</usr/lib/lpsched> is started.  Add the option "-nobsd" to the line.
That will make sure LP doesn't grab the port at the next reboot.  So that you
don't have to reboot after making the change, run these commands:

 # /usr/lib/lpshut
 # /usr/lib/lpsched -nobsd

=head3 SunOS 5.6 (Solaris 2.6)

If you are using SunOS 5.6 (Solaris 2.6) then you need only edit /etc/inetd.conf
and remove the line which reads:

    printer stream tcp nowait root /usr/lib/print/in.lpd in.lpd

Before this change will take effect, it is necessary to tell B<inetd> to reload
F<inetd.conf> by sending it the HUP signal.  If B<inetd> has the process id 123,
then the command for reloading F<inetd.conf> is:

    kill -HUP 123

or, if your B<kill> command doesn't support the modern syntax:

    kill -1 123

=head3 CUPS

[Information missing.]


=head2 Recommended Setup

By default B<pprd> will listen on port 515 and launch B<lprsrv> whenever a
new connexion comes in.  This feature will be enabled only if port 515 is
free and B<pprd> is started as root.


=head2 Alternative Setup With Inetd

If you are hacking PPR, you may want to be able to start and stop B<pprd> 
without having root access.  In that case, you should configure 
B<inetd> to launch B<lprsrv> as user B<ppr>.  The configuration 
line to insert in F</etc/inetd.conf>.

    printer stream tcp nowait ppr /usr/lib/ppr/lprsrv lprsrv


=head2 Queue Listing Options

When a client requests a queue listing for a PPR queue, B<lprsrv> will
return the output of B<ppop lpq> for the short format and B<ppop list> for
the long format.  The B<ppop lpq> output is designed to look similiar to the
output of BSD B<lpq>.

If the B<-A> switch is used, B<lprsrv> will pass the switch and its argument
on to B<ppop>.  The argument is an integer which indicates an age in
seconds.  Arrested jobs older than the specified age will not be shown in
queue listings.

When a client requests a queue listing for an LPR/LPD queue, B<lprsrv>
simply executes B<lpq> and returns the output.

When a client requests a queue listing for a System V B<lp> queue, B<lprsrv>
runs B<lpstat>.  Some B<lpq> options are not supported for B<lp> queues.


=head2 Access Control

Access to queues through B<lprsrv> is controled by the file
F</etc/ppr/lprsrv.conf>.  The only documentation currently available is in
F</etc/ppr/lprsrv.conf.sample>.

If you use an unmodified F<lprsrv.conf.sample> for F<lprsrv.conf>, then
tranditional BSD-style access control will be in effect.  Under this style
of access control, any computer listed in F</etc/hosts.equiv> or
F</etc/hosts.lpd> will be allowed to submit jobs.  The names listed in these
files should be fully qualified names.

Since B<lprsrv> uses its own code, it may not support all of the access
control syntax described in L<hosts.equiv>.  In particular, "+" and "-" are
not supported.  Domain wildcards such as ".trincoll.edu" are supported.  NIS
netgroup support is available on some systems.

If you would like to add support for additional access control syntax in
F</etc/hosts.equiv> and F</etc/hosts.lpd>, you should modify the function
authorized_file_check() in lprsrv/lprsrv_conf.c.  If you make improvements,
please consider contributing them to the PPR project.


=head2 Access Control Testing

The program B<lprsrv-test> can be used to test the rules in F</etc/ppr/lprsrv.conf>,
F</etc/hosts.equiv>, and F</etc/hosts.lpd>.

You can use it to find out what sort of access certain users on a certain
host will have.  When you run it the first parameter should be a
hostname.  The second and subsequent parameters should be usernames.

Since several sections of F</etc/ppr/lprsrv.conf> may be combined to
determine the access settings for a certain host, it can be difficult to
determine exactly what access a particular host has.  B<lprsrv-test> solves
this by printing a merged record in F</etc/ppr/lprsrv.conf> format which
shows the final settings which apply to the host you named on the command
line.

For each remote user you name on the command line, B<lprsrv-test> will print
the name of the local user which will be used to execute spooler commands on
the remote user's behalf.  The local user used may be different for each
spooler.


=head2 Other Options

=over 4

=item B<-A> I<seconds>

=item B<--arrest-interest-interval> I<seconds>

Whenever B<lprsrv> lists a PPR queue, the argument to either of these
switches is passed to the B<ppop> command as an argument for its B<-A> switch.

=back


=head2 Support for DEC RFC-1179 Extensions

The version of B<lpr> supplied with DEC OSF/1 has many more options than the
BSD version.  Using these extra options results in extra lines in the queue
file which B<lpr> sends to B<lprsrv>.  These extensions are supported by
B<lprsrv> whenever possible.


=head2 Support for Solaris RFC-1179 Extensions

The print spooler in Solaris 2.6 (SunOS 5.6) is derived from the System V
LP spooler.  When it sends jobs using the RFC-1179 protocol it include extra
control file lines which represent System V B<lp> options.  These
extensions are supported by B<lprsrv> whenever possible.


=head2 Using Switchsets with B<lprsrv>

The B<lprsrv> configuration file does not provided any way for setting
options for individual queues.  It is suggested that you use the B<ppad switchset>,
B<ppad group switchset> and B<ppad alias switchset> commands do do this.  See
the B<ppad switchset> description for examples.

Be aware that B<lprsrv> will sometimes override switchset options.  It will always
override an B<-m> option (which shouldn't be in a switchset anyway).  It will also
override duplex, paper source, and other options if conflicting instructions
are conveyed by means of Solaris or DEC extensions to the RFC-1179 protocol.


=head2 Banner Pages

The RFC 1179 protocol provides a way for a client to ask to have banner pages
suppressed.  (The BSD B<lpr -h> option uses this feature.)  If B<lprsrv>
receives a job that requests suppression of the banner page, it will attempt
to do so.  However, suppressing the banner page may not be allowed.  In that
case, the spooler to which B<lprsrv> submits the job will likely print a banner
page anyway.

In the case of a PPR printer, if the B<ppad flags> command has been used to
set the printer's banner option to B<always>, then it will not be possible for
an RFC 1179 client to suppress the banner page.

In the case of a System V B<lp> queue, an RFC 1179 client will probably not
be able to suppress the banner page unless the B<lpadmin -o> option has
been used to set a list of printer options which includes "nobanner".


=head2 Client Configuration

This section describes the commands needed to set up various print spoolers
as clients of B<lprsrv>.  If you have information to add to this section,
please send it to ppr-bugs@trincoll.edu.

=head3 BSD lpr

Add an entry similar to the following to F</etc/printcap>.

    myprn|My Printer:\
	:rp=somehost.mycoll.edu:rm=myprn:\
	:sd=/var/spool/lpd/myprn:\
	:mx#0:

Then create the local spool directory.

    mkdir /var/spool/lpd/myprn

=head1 SEE ALSO

See the comments in F</etc/ppr/lprsrv.conf>.

=head1 HISTORY

PPR was written at Trinity College during 1993--2005.

=head1 AUTHORS

David Chappell, Trinity College Computing Center, Hartford, Connecticut.

=cut

