#
# mouse:~ppr/src/docs/refman/papd.8.pod
# Copyright 1995--2004, Trinity College Computing Center.
# Written by David Chappell.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
#
# Last modified 29 January 2004.
#

=head1 NAME

B<papd> - New AppleTalk Printer Access Protocol Server

=head1 SYNOPSIS

B<papd> [--help] [--version] [--foreground] [--stop] [--reload]

=head1 DESCRIPTION

This program is PPR's new and unfinished AppleTalk Printer Access Protocol
(PAP) server.  The options are as follows:

=over 4

=item B<--help>

Print a short summary of the options.

=item B<--version>

Print the PPR version number and revision date.

=item B<--foreground>

Run as a server, but don't attempt to run in the background.  Output which
would ordinarily go to the log file will go to stderr instead.

=item B<--stop>

Stop any previously started instance of B<papd> which may be running as a
server.

=item B<--reload>

Re-examine the alias, group, and printer configuration files and unadvertise
names which are no longer called for and advertise any new ones.  On Linux
2.4.19 and later (with a sufficiently recent version of Glibc) this will 
happen automatically.

=back

By default, queues are not shared using AppleTalk.  To share a queue, you must assign
it an AppleTalk name.  The name is stored in the queue's configuration file as an
add-on parameter.  You can do that with the B<ppad addon> command.  For example:

	$ ppad addon myprn papd "My Printer"

If the name should appear on the network within a few seconds.  If not, look in
F</var/spool/ppr/logs/papd> to see what went wrong.  You may have to tell 
B<papd> to reload its configuration file, like so:

	$ papd --reload
	Sending Hangup to papd (PID=31791).

To remove the name, simply set the papd parameter but leave off the value.

	$ ppad addon myprn papd

If necessary, tell B<papd> to reload.  If you look F</var/spool/ppr/logs/papd>, you will
see that B<papd> has rescanned the queue configuration files and that this time the
papd add-on parameter is absent, so the name was removed from the network.

To change the name, simply set a new one.  The old one will be removed and the new one added 
when B<papd> reloads.

Sharing aliases and groups is quite simple.  One simply uses the B<ppad> commands for 
setting alias and group add-on parameters:

	$ ppad group addon mygroup "My Group"
	$ ppad alias addon myalias "My Alias"

=head1 FILES

This program reads the [papd] section in F</etc/ppr/ppr.conf>.  It also
reads the alias, group, and printer configuration files in
F</etc/ppr/aliases>, F</etc/ppr/groups>, and F</etc/ppr/printers>
respectively.  The daemon's PID is stored in F</var/spool/ppr/run/papd.pid>. 
Its actions are logged in F</var/spool/ppr/logs/papd>.

=head1 SEE ALSO

"PPR, a PostScript Print Spooler"

=head1 HISTORY

PPR was written at Trinity College during 1993--2004.
It was first released to the public on 26 April 1995.

=head1 AUTHOR

David Chappell, Trinity College Computing Center, Hartford, Connecticut.

=cut
