#
# mouse:~ppr/src/docs/refman/papd.8.pod
# Copyright 1995--2003, Trinity College Computing Center.
# Written by David Chappell.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
#
# Last modified 15 January 2003.
#

=head1 NAME

B<papd> - New AppleTalk Printer Access Protocol Server

=head1 SYNOPSIS

B<papd> [--help] [--version] [--foreground] [--stop] [--reload]

=head1 DESCRIPTION

This program is PPR's new and unfinished AppleTalk Printer Access Protocol
(PAP) server.  The options are as follows:

=over 4

=item B<--help>

Print a short summary of the options.

=item B<--version>

Print the PPR version number and revision date.

=item B<--foreground>

Run as a server, but don't attempt to run in the background.  Output which
would ordinarily go to the log file will go to stderr instead.

=item B<--stop>

Stop any previously started instance of B<papd> which may be running as a
server.

=item B<--reload>

Re-examine the alias, group, and printer configuration files and unadvertise
names which are no longer called for and advertise any new ones.  On Linux
2.4.19 and later this will happen automatically.

=back

=head1 FILES

This program reads the [papd] section in F</etc/ppr/ppr.conf>.  It also
reads the alias, group, and printer configuration files in
F</etc/ppr/aliases>, F</etc/ppr/groups>, and F</etc/ppr/printers>
respectively.  The daemon's PID is stored in F</var/spool/ppr/run/papd.pid>. 
Its actions are logged in F</var/spool/ppr/logs/papd>.

=head1 SEE ALSO

"PPR, a PostScript Print Spooler"

=head1 HISTORY

PPR was written at Trinity College during 1993--2003.
It was first released to the public on 26 April 1995.

=head1 AUTHOR

David Chappell, Trinity College Computing Center, Hartford, Connecticut.

=cut
