#
# mouse:~ppr/src/docs/refman/ppr-testpage.1.pod
# Copyright 1995--2004, Trinity College Computing Center.
# Written by David Chappell.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
#
# Last modified 27 May 2004.
#

=head1 NAME

ppr-testpage - generate a test page

=head1 SYNOPSIS

B<ppr-testpage> [options]

=head1 DESCRIPTION

This program genenerates a PostScript testpage and prints it on standard
output.  Normally this testpage has the PPR logo in the upper right hand
corner, multiple margin lines as an aid in locating unprintable areas, and 
the printers product string and PostScript version and revision numbers. 
The test page's features may be alterned by using the options listed below.

=over 4

=item --pagesize=I<pagesize>

Format the test page for the indicated page size.  Valid values include
B<Letter>, B<Legal>, B<A4>, and all the other sizes defined in the PPD file
specification.  The default is B<Letter>.

=item --eps-file=I<filename>

Replace the PPR logo at the upper right hand of the the test page with the
indicated EPS file.

=item --eps-scale=I<float>

Multiply the size of the EPS file by the indicated factor.  A factor of 1.0
will print the EPS figure at its intrisic size.

=item --test-grayscale

Print a grayscale density bar.

=item --test-rgb

Print density bars for red, green, and blue.  Zero density will be black
since zero represents no illumination.

=item --test-cmyk

Print density bars for cyan, magenta, yellow and black (k).  Zero density
will be white (assuming white paper) since zero represents no ink
appication.

=item --test-spoked

Print a spoked wheel with a radius of 125 points.  The spokes are at 1 degree
intervals.  The lines are as thin as the printer is capable of printing.  Rings
printed at 25 point intervals out from the center enable one to judge how 
closely lines may be printed while still being distringuishable.

=item --version

Print PPR version information.

=item --help

Print brief usage summary on stdout.

=back

=head1 EXAMPLE

Since this program doesn't actually print the test page (in the sense of
sending it to a printer and putting marks on paper) we must pipe its output
to a command such B<ppr> in order to get it printed.  For example:

	$ ppr-testpage --test-cmyk | ppr -d myprn

This command will print a test page with CMYK color bars on myprn.

=head1 SEE ALSO

"PPR, a PostScript Print Spooler"

=head1 HISTORY

PPR was written at Trinity College during 1993--2003.

=head1 AUTHOR

David Chappell, Trinity College Computing Center, Hartford, Connecticut.

=cut
