#
# mouse:~ppr/src/docs/refman/ppr-web.1.pod
# Copyright 1995--2003, Trinity College Computing Center.
# Written by David Chappell.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
#
# Last modified 6 March 2003.
#

=head1 NAME

B<ppr-web> - Open PPR's Web-based Control Panel

=head1 SYNOPSIS

B<ppr-web> [I<destname> [I<filename>] ... ] 

=head1 DESCRIPTION

This command attempts to open the PPR web interface in a web browser.  If
it is running under X-Windows and Mozilla is available, that is what will be
used since it is the browser which best displays the PPR web interface.  It
X-Windows is not available, Links will be used in text mode.

=head2 Control Panel

If no arguments are supplied, then the PPR control panel will be opened.

=head2 Queue Display

If one argument, a queue name, is supplied, then a queue display window is
opened.

=head2 Job Submission

If two or more arguments are supplied, the first is understood to be the
queue name and the second and subsequent arguments are understood to be the
names of files to be submitted to that queue.  There will be no GUI
manifestation of this operation, though a print dialog is planned for the
future.

=head2 KDE Icons

This command is the action command of KDE icons which you can double click
on to open a queue or drop files onto to print them.  To create such an
icon, click on the queue's icon in the Control Panel and choose the B<Client
Configuration> item.  You will be able to choose to create an KDE icon.  You
can save the icon on your desktop (or anywhere else for that matter).

=head1 SEE ALSO

"PPR, a PostScript Print Spooler"

=head1 HISTORY

PPR was written at Trinity College during 1993--2003.

=head1 AUTHOR

David Chappell, Trinity College Computing Center, Hartford, Connecticut.

=cut
