#! /bin/sh

if [ $1 = "--wiz" ]
    then
    shift
    # Convert a 6.375" square FIG image to a 128 pixel square PNG image.
    #fig2dev -L png -m 1.0 $1.fig | pngtopnm | pnmscale 0.250 | pnmtopng > $1.png
    fig2dev -L ppm -m 1.0 $1.fig | pnmscale 0.250 | pnmtopng > $1.png

    else
    # Render the image at 4x and then scale it down with anti-aliasing.
    #fig2dev -L png -m 4.0 $1.fig | pngtopnm | pnmscale 0.250 | pnmtopng > $1.png
    fig2dev -L ppm -m 4.0 $1.fig | pnmscale 0.250 | pnmtopng > $1.png

    fi

exit $?
