#! /usr/bin/perl -w
#
# mouse:~ppr/src/editps/Windows_XP
# Copyright 1995--2005, Trinity College Computing Center.
# Written by David Chappell.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
#
# Last modified 10 June 2005.
#

#
# This filter is for Microsoft Windows XP's PostScript driver (PScript5.dll
# version 5.2*).  For some reason, it (or at least some versions) omits the
# "%%Page:" comments.  We look for the proper context and insert them.
#

my $page = 1;
my $pages_seen = 0;
while(my $line = <STDIN>)
	{
	if($line =~ /^%%Page:/)
		{
		$pages_seen++;
		}
	elsif($line eq "%%EndPageComments\r\n")
		{
		if($pages_seen < $pages)		# if %%Page comment is missing,
			{
			print "%%Page: $page $page\n";
			$page++;
			}
		}

	$line =~ s/^(%%IncludeResource:) ProcSet /$1 procset /;

	print $line;
	}

exit 0;
