#
# mouse:~ppr/src/fonts/Makefile
# Copyright 1995--2000, Trinity College Computing Center.
# Written by David Chappell.
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose and without fee is hereby granted, provided
# that the above copyright notice appear in all copies and that both that
# copyright notice and this permission notice appear in supporting
# documentation.  This software is provided "as is" without express or
# implied warranty.
#
# Last modified 22 November 2000.
#

include ../Makefile.conf

all:

install: fontsub.conf fonts.conf
	$(INSTALLDATA) $(SHAREDIR)/lib fontsub.conf fonts.conf

depend:

clean:
	$(RMF) $(BACKUPS)

# end of file
