#! /bin/sh
# postrm script for ppr

set -e

if [ "$1" = "purge" ]
	then
	update-rc.d ppr remove >/dev/null
	rm -f /etc/default/ppr
	rm -f /var/spool/ppr/run/lastid_ppr
	rm -f /var/spool/ppr/run/lastid_uprint_lpr
	rm -r /var/spool/ppr/PIPE
	if getent passwd ppr >/dev/null ; then
		echo "Removing user ppr" 1>&2
		deluser ppr
		fi
	if getent passwd pprwww >/dev/null ; then
		echo "Removing user pprwww" 1>&2
		deluser pprwww
		fi
	if getent group ppr >/dev/null ; then
		echo "Removing group ppr" 1>&2
		delgroup ppr
		fi
	fi

#DEBHELPER#

exit 0
