#! /bin/sh
# preinst script for ppr

set -e

if ! getent passwd ppr >/dev/null ; then
	echo 'Adding system-user ppr' 1>&2
	adduser --system --group --home /usr/lib/ppr --no-create-home \
		--disabled-login --force-badname ppr > /dev/null
	fi
if ! getent passwd pprwww >/dev/null ; then
	echo 'Adding system-user pprwww' 1>&2
	adduser --system --ingroup ppr --home /usr/lib/ppr --no-create-home \
		--disabled-login --force-badname pprwww > /dev/null
	fi

#DEBHELPER#

exit 0
