#!/bin/sh
#
# This tests the handling of various DSC syntax errors.
#
# Last modified 19 September 1997.
#

# Make sure a trailer comment doesn't work without atend.
$TESTBIN/clear_output
$HOMEDIR/bin/ppr -d regression-test1 -w peeve -r none <<EndOfSample1 || echo "ppr: $?"
%!PS-Adobe-3.0
%%PageOrder:Ascend
%%Title: atend test 1
%%VeryLongAndImprobableDSCCommentToTestWarnings: fred sam dick
%%+ lucy susan
%%Pages:(atend)

%%EndProlog

%%Page: 1 1
showpage

%%Page:2 2
showpage

%%Trailer
%%Pages: 2
%%EOF
EndOfSample1
$TESTBIN/cat_output || echo "error!"

exit 0
