#!/bin/sh
#
# Test the handling of improperly inserted EPS documents.
#
# Last modified 12 September 1997.
#

$TESTBIN/clear_output
$PPR_PATH -d regression-test1 -w peeve -m none <${TEST_BASENAME}-1.ps
$TESTBIN/cat_output

$TESTBIN/clear_output
$PPR_PATH -d regression-test1 -w peeve -m none -H badeps <${TEST_BASENAME}-1.ps
$TESTBIN/cat_output

$TESTBIN/clear_output
$PPR_PATH -d regression-test1 -w peeve -m none <${TEST_BASENAME}-2.ps
$TESTBIN/cat_output

$TESTBIN/clear_output
$PPR_PATH -d regression-test1 -w peeve -m none -H badeps <${TEST_BASENAME}-2.ps
$TESTBIN/cat_output

exit 0
