# Bourne shell translation of interface.h
EXIT_PRINTED=0				#/* file was printed normally */
EXIT_PRNERR=1				#/* printer error occured */
EXIT_PRNERR_NORETRY=2			#/* printer error with no hope of retry */
EXIT_JOBERR=3				#/* job is defective */
EXIT_SIGNAL=4				#/* terminated after catching signal */
EXIT_ENGAGED=5				#/* printer is otherwise engaged (connection refused) */
EXIT_STARVED=6				#/* starved for system resources */
EXIT_PRNERR_NORETRY_ACCESS_DENIED=7	#/* bad password? bad port permissions? */
EXIT_PRNERR_NOT_RESPONDING=8		#/* just doesn't answer at all (turned off?) */
EXIT_PRNERR_NORETRY_BAD_SETTINGS=9	#/* interface settings are invalid */
EXIT_PRNERR_NO_SUCH_ADDRESS=10		#/* address lookup failed, may be transient */
EXIT_PRNERR_NORETRY_NO_SUCH_ADDRESS=11	#/* address lookup failed, not transient */
EXIT_INCAPABLE=50			#/* printer wants (lacks) features or resources */
JOBBREAK_NONE=0				#/* unusable */
JOBBREAK_SIGNAL=1			#/* SIGUSR1 handshake (tricky) */
JOBBREAK_CONTROL_D=2			#/* simple control-D protocol */
JOBBREAK_PJL=3				#/* HP's Printer Job Language */
JOBBREAK_SIGNAL_PJL=4			#/* SIGUSR1 handshake and PJL */
JOBBREAK_SAVE_RESTORE=5			#/* silly too */
JOBBREAK_NEWINTERFACE=6			#/* lame */
