#!/bin/sh

export XAUTHORITY=/var/spool/ppr/run/Xauthority

unset LANGUAGE
unset `env | grep ^LC_ | cut -f1 -d=`

LANG=ru_RU.koi8r
OUTPUT_CHARSET=koi8r
export LANG OUTPUT_CHARSET

xterm -font "-*-*-*-r-*-*-*-140-*-*-m-*-koi8-r" -e joe -asis $*

exit 0
