#! /bin/sh
#
# Make sure PPD *Include works correctly.
#

$PPAD_PATH ppd regression-test1 `pwd`/test-pprdrv/includer.ppd
echo "ppad: $?"

$TESTBIN/clear_output

$PPR_PATH -d regression-test1 -m none -f ppr <<EndOfSample
%!PS-Adobe-3.0

%%EndProlog

%%BeginSetup
%%IncludeFeature: *InputSlot Upper
%%IncludeFeature: *InputSlot Lower
%%IncludeFeature: *InputSlot Middle
%%EndSetup

%%Page: 1 1
showpage

%%EOF
EndOfSample

echo "ppr: $?"

$TESTBIN/cat_output

exit 0
