#!/bin/sh
#
# Make PPD *Include works correctly.
#

$TESTBIN/clear_output

$PPR_PATH -d regression-test1 -m none -u yes <<EndOfSample
%!PS-Adobe-3.0
%%Pages: 0

%%EndProlog

%%BeginSetup
%%BeginFeature: *Duplex NotaFeature
(I am not a duplex feature) print
%%EndFeature
%%EndSetup

%%EOF
EndOfSample

echo "ppr: $?"

$TESTBIN/cat_output

$TESTBIN/clear_output

$PPR_PATH -d regression-test1 -K false -m none -u yes <<EndOfSample
%!PS-Adobe-3.0
%%Pages: 0

%%EndProlog

%%BeginSetup
%%BeginFeature: *Duplex NotaFeature
(I am not a duplex feature) print
%%EndFeature
%%EndSetup

%%EOF
EndOfSample

echo "ppr: $?"

$TESTBIN/cat_output

exit 0
