#! /bin/sh

# Set up a test print queue:
$PPAD_PATH delete regression-test2 >/dev/null 2>&1
$PPAD_PATH interface regression-test2 $TESTBIN/test_interface_1 $REGTEST_INTERFACE_OUTPUT
echo "ppad: $?"
$PPAD_PATH jobbreak regression-test2 none
echo "ppad: $?"

echo "CustomHook: 63 $TESTBIN/test_custom_hook" >>$CONFDIR/printers/regression-test2

$TESTBIN/clear_output

$PPR_PATH -d regression-test2 -b yes -t yes -m none -u yes <<TestText
Now is the time for all good men to come to the aid of the party.
TestText
echo "ppr: $?"

$TESTBIN/cat_output

$PPAD_PATH delete regression-test2
echo "ppad: $?"

exit 0
