#! /bin/sh

echo "Setting jobbreak to signal/pjl..."
$PPAD_PATH jobbreak regression-test1 signal/pjl
echo "ppad: $?"
echo
$TESTBIN/dump_printer regression-test1

echo "Setting jobbreak to default..."
$PPAD_PATH jobbreak regression-test1 default
echo "ppad: $?"
echo
$TESTBIN/dump_printer regression-test1

echo "Setting feedback to true..."
$PPAD_PATH feedback regression-test1 true
echo "ppad: $?"
echo
$TESTBIN/dump_printer regression-test1

echo "Setting feedback to false..."
$PPAD_PATH feedback regression-test1 false
echo "ppad: $?"
echo
$TESTBIN/dump_printer regression-test1

echo "Setting feedback to default..."
$PPAD_PATH feedback regression-test1 default
echo "ppad: $?"
echo
$TESTBIN/dump_printer regression-test1

echo "Setting codes to Clean7Bit..."
$PPAD_PATH codes regression-test1 clean7bit
echo "ppad: $?"
echo
$TESTBIN/dump_printer regression-test1

echo "Setting codes to default..."
$PPAD_PATH codes regression-test1 default
echo "ppad: $?"
echo
$TESTBIN/dump_printer regression-test1

echo "Setting interface options..."
$PPAD_PATH options regression-test1 "sleep=10 retry=5"
echo "ppad: $?"
echo
$TESTBIN/dump_printer regression-test1

echo "Shooting for warning..."
$PPAD_PATH options regression-test1 none
echo "ppad: $?"
echo
$TESTBIN/dump_printer regression-test1

echo "Setting interface options..."
$PPAD_PATH options regression-test1 sleep=10 retry=5
echo "ppad: $?"
echo
$TESTBIN/dump_printer regression-test1

echo "Clearing interface options..."
$PPAD_PATH options regression-test1
echo "ppad: $?"
echo
$TESTBIN/dump_printer regression-test1

echo "Setting up for next test..."
$PPAD_PATH jobbreak regression-test1 signal/pjl
echo "ppad: $?"
$PPAD_PATH feedback regression-test1 false
echo "ppad: $?"
$PPAD_PATH options regression-test1 sleep=10 retry=5
echo "ppad: $?"
$PPAD_PATH codes regression-test1 Clean7Bit
echo "ppad: $?"
echo
$TESTBIN/dump_printer regression-test1

echo "Testing auto-clearing of jobbreak, feedback, codes, and options..."
$PPAD_PATH interface regression-test1 tcpip localhost:9100
echo "ppad: $?"
echo
$TESTBIN/dump_printer regression-test1

echo "Putting things back the way they were..."
$PPAD_PATH interface regression-test1 dummy "/dev/lp0"
echo "ppad: $?"
echo

exit 0
